### ISSUE TITLE
Add form for entering case data

### ISSUE THREAD

**Issue by brittberwanger** [codefortulsa/courtbot#7]
Provide a form that captures the following information and saves that to the CourtbotDB

1. Case number
2. Client name
3. Client phone number (and other interested parties' phone numbers)

**Comment by brittberwanger** [comment]
We can hook this into the API mentioned in #10, so a user can enter a case number, we grab them a list of parties real quick (so we can be certain on name spelling and formatting), they pick their party, and start adding phone numbers.

**Comment by pipakin** [comment]
Completed with courtbook's release.
